# Generated by Django 5.2.6 on 2025-11-30 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=False, verbose_name='手動入力')),
                ('source_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='基にしたニュースタイトル')),
                ('question_text', models.TextField(verbose_name='お題の本文')),
                ('theme', models.CharField(max_length=50, verbose_name='テーマ')),
                ('is_excellent', models.BooleanField(default=False, verbose_name='特に面白い')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_questions', to=settings.AUTH_USER_MODEL, verbose_name='作成/入力ユーザー')),
            ],
            options={
                'verbose_name': 'お題',
                'verbose_name_plural': 'お題',
                'ordering': ['-created_at'],
            },
        ),
    ]
