# Generated by Django 5.2.6 on 2025-12-06 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiri', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='回答内容')),
                ('score', models.IntegerField(help_text='5段階評価', verbose_name='面白さの点数')),
                ('review_text', models.TextField(verbose_name='AIの講評')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日時')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='oogiri.question', verbose_name='対象のお題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='回答ユーザー')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'ordering': ['-created_at'],
            },
        ),
    ]
