# Generated by Django 5.2.6 on 2025-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oogiri', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_excellent_answer',
            field=models.BooleanField(default=False, verbose_name='特に面白い（模範回答）'),
        ),
    ]
